//! App-managed storage for imported originals and backup staging.
//!
//! Files live under `<app_data_dir>/files/<key>`. Keys are generated by the
//! frontend (UUID + extension) and validated here so a key can never escape the
//! storage directory.

use std::fs;
use std::io::Write;
use std::path::PathBuf;
use tauri::ipc::{InvokeBody, Request, Response};

pub struct FileRoot(pub PathBuf);

fn valid_key(key: &str) -> bool {
    !key.is_empty()
        && key.len() <= 128
        && key
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.')
        && !key.starts_with('.')
        && !key.contains("..")
}

fn path_for(root: &FileRoot, key: &str) -> Result<PathBuf, String> {
    if !valid_key(key) {
        return Err("invalid file key".into());
    }
    Ok(root.0.join(key))
}

/// Body: raw bytes. Header `x-file-key`: storage key.
#[tauri::command]
pub fn file_put(root: tauri::State<'_, FileRoot>, request: Request<'_>) -> Result<u64, String> {
    let key = request
        .headers()
        .get("x-file-key")
        .and_then(|v| v.to_str().ok())
        .ok_or("missing x-file-key header")?
        .to_string();
    let InvokeBody::Raw(data) = request.body() else {
        return Err("expected raw bytes".into());
    };
    let path = path_for(&root, &key)?;
    fs::create_dir_all(&root.0).map_err(|e| e.to_string())?;
    // Write to a temp file then rename so a crash never leaves a partial original.
    let tmp = root.0.join(format!("{key}.partial"));
    {
        let mut f = fs::File::create(&tmp).map_err(|e| e.to_string())?;
        f.write_all(data).map_err(|e| e.to_string())?;
        f.sync_all().map_err(|e| e.to_string())?;
    }
    fs::rename(&tmp, &path).map_err(|e| e.to_string())?;
    Ok(data.len() as u64)
}

#[tauri::command]
pub fn file_get(root: tauri::State<'_, FileRoot>, key: String) -> Result<Response, String> {
    let path = path_for(&root, &key)?;
    let bytes = fs::read(path).map_err(|e| format!("read stored file: {e}"))?;
    Ok(Response::new(bytes))
}

#[tauri::command]
pub fn file_delete(root: tauri::State<'_, FileRoot>, key: String) -> Result<(), String> {
    let path = path_for(&root, &key)?;
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.to_string()),
    }
}

#[tauri::command]
pub fn file_list(root: tauri::State<'_, FileRoot>) -> Result<Vec<String>, String> {
    let mut out = Vec::new();
    let Ok(rd) = fs::read_dir(&root.0) else {
        return Ok(out);
    };
    for entry in rd.flatten() {
        if let Some(name) = entry.file_name().to_str() {
            if valid_key(name) && !name.ends_with(".partial") {
                out.push(name.to_string());
            }
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::valid_key;

    #[test]
    fn rejects_traversal() {
        assert!(valid_key("abc-123.pdf"));
        assert!(!valid_key("../x"));
        assert!(!valid_key("a/b"));
        assert!(!valid_key("a\\b"));
        assert!(!valid_key(".hidden"));
        assert!(!valid_key(""));
    }
}
